<div class="admin-header-bar">
    <h1>Vytvořit novou stránku</h1>
    <a href="<?= adminUrl('pages') ?>" class="btn btn-secondary">Zpět na seznam</a>
</div>

<div class="form-container">
    <form method="POST" action="<?= adminUrl('pages/store') ?>" class="admin-form">
        <?= csrfField() ?>

        <h2 class="section-title">Základní nastavení</h2>

        <div class="form-group">
            <label for="title_cs">Název stránky (Česky) *</label>
            <input type="text" id="title_cs" name="title_cs" required
                   value="<?= old('title_cs') ?>"
                   class="form-control" placeholder="Naše vize">
        </div>

        <div class="form-group">
            <label for="slug">Slug (URL) *</label>
            <input type="text" id="slug" name="slug" required
                   value="<?= old('slug') ?>"
                   class="form-control" placeholder="nase-vize"
                   pattern="[a-z0-9\-]+"
                   title="Pouze malá písmena, čísla a pomlčky">
            <small>URL adresa stránky (např. "nase-vize" → /cs/nase-vize). Použijte pouze malá písmena, čísla a pomlčky.</small>
        </div>

        <div class="form-group">
            <label for="has_english_version">
                <input type="checkbox" id="has_english_version" name="has_english_version" value="1" <?= old('has_english_version') ? 'checked' : '' ?>>
                Vytvořit stránku v angličtině
            </label>
            <small>Zaškrtněte pro vytvoření anglické verze stránky</small>
        </div>

        <div id="english-fields" style="display: none;">
            <div class="form-group">
                <label for="title_en">Název stránky (Anglicky)</label>
                <input type="text" id="title_en" name="title_en"
                       value="<?= old('title_en') ?>"
                       class="form-control" placeholder="Our Vision">
            </div>

            <div class="form-group">
                <label for="slug_en">Slug EN (URL)</label>
                <input type="text" id="slug_en" name="slug_en"
                       value="<?= old('slug_en') ?>"
                       class="form-control" placeholder="our-vision"
                       pattern="[a-z0-9\-]+"
                       title="Pouze malá písmena, čísla a pomlčky">
                <small>URL adresa anglické stránky (např. "our-vision" → /en/our-vision)</small>
            </div>
        </div>

        <div class="form-group">
            <label for="published">
                <input type="checkbox" id="published" name="published" value="1" checked>
                Publikováno
            </label>
            <small>Zaškrtněte pro okamžité zveřejnění stránky</small>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Vytvořit stránku</button>
            <a href="<?= adminUrl('pages') ?>" class="btn btn-secondary">Zrušit</a>
        </div>
    </form>
</div>

<script>
// Show/hide English fields based on checkbox
const hasEnglishCheckbox = document.getElementById('has_english_version');
const englishFields = document.getElementById('english-fields');

function toggleEnglishFields() {
    if (hasEnglishCheckbox.checked) {
        englishFields.style.display = 'block';
    } else {
        englishFields.style.display = 'none';
    }
}

// Initial state
toggleEnglishFields();

hasEnglishCheckbox.addEventListener('change', toggleEnglishFields);

// Auto-generate slug CS from Czech title
const titleCs = document.getElementById('title_cs');
const slugInput = document.getElementById('slug');

titleCs.addEventListener('input', function() {
    if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
        const slug = this.value
            .toLowerCase()
            .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // Remove diacritics
            .replace(/[^a-z0-9\s\-]/g, '') // Remove special chars
            .trim()
            .replace(/\s+/g, '-') // Spaces to hyphens
            .replace(/-+/g, '-'); // Multiple hyphens to single

        slugInput.value = slug;
        slugInput.dataset.autoGenerated = 'true';
    }
});

slugInput.addEventListener('input', function() {
    this.dataset.autoGenerated = 'false';
});

// Auto-generate slug EN from English title
const titleEn = document.getElementById('title_en');
const slugEnInput = document.getElementById('slug_en');

titleEn.addEventListener('input', function() {
    if (!slugEnInput.value || slugEnInput.dataset.autoGenerated === 'true') {
        const slug = this.value
            .toLowerCase()
            .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // Remove diacritics
            .replace(/[^a-z0-9\s\-]/g, '') // Remove special chars
            .trim()
            .replace(/\s+/g, '-') // Spaces to hyphens
            .replace(/-+/g, '-'); // Multiple hyphens to single

        slugEnInput.value = slug;
        slugEnInput.dataset.autoGenerated = 'true';
    }
});

slugEnInput.addEventListener('input', function() {
    this.dataset.autoGenerated = 'false';
});
</script>

<style>
.admin-header-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding-bottom: 20px;
    border-bottom: 2px solid #e1e8ed;
}

.admin-header-bar h1 {
    margin: 0;
    font-size: 28px;
    color: #333;
}

.form-container {
    background: white;
    border-radius: var(--border-radius, 8px);
    box-shadow: var(--shadow);
    padding: 30px;
}

.admin-form {
    max-width: 800px;
}

.section-title {
    font-size: 20px;
    font-weight: 600;
    color: #333;
    margin-bottom: 25px;
    padding-bottom: 15px;
    border-bottom: 2px solid #e1e8ed;
}

.form-group {
    margin-bottom: 25px;
}

.form-group label {
    display: block;
    margin-bottom: 8px;
    font-weight: 600;
    color: #333;
    font-size: 14px;
}

.form-control {
    width: 100%;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: var(--border-radius, 8px);
    font-size: 14px;
    font-family: inherit;
    transition: all 0.3s;
}

.form-control:focus {
    outline: none;
    border-color: var(--color-primary, #00792E);
    box-shadow: 0 0 0 3px rgba(0, 121, 46, 0.1);
}

.form-control:invalid {
    border-color: #dc3545;
}

textarea.form-control {
    resize: vertical;
    font-family: monospace;
}

select.form-control {
    cursor: pointer;
}

.form-group small {
    display: block;
    margin-top: 6px;
    color: #666;
    font-size: 13px;
}

.form-group input[type="checkbox"] {
    width: auto;
    margin-right: 8px;
}

.form-actions {
    display: flex;
    gap: 15px;
    margin-top: 40px;
    padding-top: 30px;
    border-top: 2px solid #e1e8ed;
}

.btn {
    padding: 12px 24px;
    border: none;
    border-radius: var(--border-radius, 8px);
    font-size: 15px;
    font-weight: 600;
    cursor: pointer;
    text-decoration: none;
    display: inline-block;
    transition: all 0.3s;
}

.btn-primary {
    background: var(--color-primary, #00792E);
    color: white;
}

.btn-primary:hover {
    background: #005a20;
    transform: translateY(-2px);
    box-shadow: var(--shadow);
}

.btn-secondary {
    background: #6c757d;
    color: white;
}

.btn-secondary:hover {
    background: #5a6268;
}
</style>
