<div class="admin-header-bar">
    <h1>Vytvořit novou stránku</h1>
    <a href="<?= adminUrl('pages') ?>" class="btn btn-secondary">Zpět na seznam</a>
</div>

<div class="form-container">
    <form method="POST" action="<?= adminUrl('pages/store') ?>" class="admin-form">
        <?= csrfField() ?>

        <div class="form-tabs">
            <button type="button" class="tab-btn active" data-tab="basic">Základní nastavení</button>
            <button type="button" class="tab-btn" data-tab="cs">Čeština (CS)</button>
            <button type="button" class="tab-btn" data-tab="en">Angličtina (EN)</button>
        </div>

        <!-- Basic Settings Tab -->
        <div class="tab-content active" id="tab-basic">
            <div class="form-group">
                <label for="slug">Slug (URL) *</label>
                <input type="text" id="slug" name="slug" required
                       value="<?= old('slug') ?>"
                       class="form-control" placeholder="nase-vize"
                       pattern="[a-z0-9\-]+"
                       title="Pouze malá písmena, čísla a pomlčky">
                <small>URL adresa stránky (např. "nase-vize" → /cs/nase-vize). Použijte pouze malá písmena, čísla a pomlčky.</small>
            </div>

            <div class="form-group">
                <label for="template">Šablona</label>
                <select id="template" name="template" class="form-control">
                    <option value="default" selected>Widgetová stránka (page builder)</option>
                    <option value="custom">Vlastní šablona (custom PHP)</option>
                </select>
                <small>Widgetová stránka umožňuje skládat obsah z widgetů v administraci</small>
            </div>

            <div class="form-group">
                <label for="published">
                    <input type="checkbox" id="published" name="published" value="1" checked>
                    Publikováno
                </label>
                <small>Zaškrtněte pro okamžité zveřejnění stránky</small>
            </div>
        </div>

        <!-- Czech Tab -->
        <div class="tab-content" id="tab-cs">
            <div class="form-group">
                <label for="title_cs">Název stránky (Česky) *</label>
                <input type="text" id="title_cs" name="title_cs" required
                       value="<?= old('title_cs') ?>"
                       class="form-control" placeholder="Naše vize">
            </div>

            <div class="form-group">
                <label for="content_cs">Obsah (Česky)</label>
                <textarea id="content_cs" name="content_cs" rows="10" class="form-control editor"><?= old('content_cs') ?></textarea>
                <small>Pro widgetovou stránku bude obsah složen z widgetů (toto pole můžete nechat prázdné)</small>
            </div>
        </div>

        <!-- English Tab -->
        <div class="tab-content" id="tab-en">
            <div class="form-group">
                <label for="title_en">Page Title (English)</label>
                <input type="text" id="title_en" name="title_en"
                       value="<?= old('title_en') ?>"
                       class="form-control" placeholder="Our Vision">
                <small>Pokud nevyplníte, použije se český název</small>
            </div>

            <div class="form-group">
                <label for="content_en">Content (English)</label>
                <textarea id="content_en" name="content_en" rows="10" class="form-control editor"><?= old('content_en') ?></textarea>
                <small>For widget pages, content will be composed of widgets</small>
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Vytvořit stránku</button>
            <a href="<?= adminUrl('pages') ?>" class="btn btn-secondary">Zrušit</a>
        </div>
    </form>
</div>

<script>
// Tab switching
document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        const targetTab = this.dataset.tab;

        // Remove active from all tabs
        document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
        document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));

        // Add active to clicked tab
        this.classList.add('active');
        document.getElementById('tab-' + targetTab).classList.add('active');
    });
});

// Auto-generate slug from Czech title
const titleCs = document.getElementById('title_cs');
const slugInput = document.getElementById('slug');

titleCs.addEventListener('input', function() {
    if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
        const slug = this.value
            .toLowerCase()
            .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // Remove diacritics
            .replace(/[^a-z0-9\s\-]/g, '') // Remove special chars
            .trim()
            .replace(/\s+/g, '-') // Spaces to hyphens
            .replace(/-+/g, '-'); // Multiple hyphens to single

        slugInput.value = slug;
        slugInput.dataset.autoGenerated = 'true';
    }
});

slugInput.addEventListener('input', function() {
    this.dataset.autoGenerated = 'false';
});
</script>

<style>
.admin-header-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding-bottom: 20px;
    border-bottom: 2px solid #e1e8ed;
}

.admin-header-bar h1 {
    margin: 0;
    font-size: 28px;
    color: #333;
}

.form-container {
    background: white;
    border-radius: var(--border-radius, 8px);
    box-shadow: var(--shadow);
    padding: 30px;
}

.admin-form {
    max-width: 800px;
}

.form-tabs {
    display: flex;
    gap: 10px;
    border-bottom: 2px solid #e1e8ed;
    margin-bottom: 30px;
}

.tab-btn {
    background: none;
    border: none;
    padding: 12px 24px;
    font-size: 15px;
    font-weight: 600;
    color: #666;
    cursor: pointer;
    border-bottom: 3px solid transparent;
    transition: all 0.3s;
}

.tab-btn:hover {
    color: #333;
    background: #f8f9fa;
}

.tab-btn.active {
    color: var(--color-primary, #00792E);
    border-bottom-color: var(--color-primary, #00792E);
}

.tab-content {
    display: none;
}

.tab-content.active {
    display: block;
}

.form-group {
    margin-bottom: 25px;
}

.form-group label {
    display: block;
    margin-bottom: 8px;
    font-weight: 600;
    color: #333;
    font-size: 14px;
}

.form-control {
    width: 100%;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: var(--border-radius, 8px);
    font-size: 14px;
    font-family: inherit;
    transition: all 0.3s;
}

.form-control:focus {
    outline: none;
    border-color: var(--color-primary, #00792E);
    box-shadow: 0 0 0 3px rgba(0, 121, 46, 0.1);
}

.form-control:invalid {
    border-color: #dc3545;
}

textarea.form-control {
    resize: vertical;
    font-family: monospace;
}

select.form-control {
    cursor: pointer;
}

.form-group small {
    display: block;
    margin-top: 6px;
    color: #666;
    font-size: 13px;
}

.form-group input[type="checkbox"] {
    width: auto;
    margin-right: 8px;
}

.form-actions {
    display: flex;
    gap: 15px;
    margin-top: 40px;
    padding-top: 30px;
    border-top: 2px solid #e1e8ed;
}

.btn {
    padding: 12px 24px;
    border: none;
    border-radius: var(--border-radius, 8px);
    font-size: 15px;
    font-weight: 600;
    cursor: pointer;
    text-decoration: none;
    display: inline-block;
    transition: all 0.3s;
}

.btn-primary {
    background: var(--color-primary, #00792E);
    color: white;
}

.btn-primary:hover {
    background: #005a20;
    transform: translateY(-2px);
    box-shadow: var(--shadow);
}

.btn-secondary {
    background: #6c757d;
    color: white;
}

.btn-secondary:hover {
    background: #5a6268;
}
</style>
