-- =====================================================
-- SEED DATA - Widget Types
-- =====================================================
-- Základní sada 9 widget typů pro page builder
-- JSON schemas jsou v kompaktním formátu pro MySQL
-- =====================================================

-- 1. HERO FULLSCREEN (Photo + Video)
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('hero', 'Hero Fullscreen', 'components/hero.php', '🖼️', 'content', '{"fields":[{"key":"title","type":"text","label":"Nadpis","translatable":true,"required":true},{"key":"subtitle","type":"text","label":"Podnadpis","translatable":true,"required":false},{"key":"mediaType","type":"select","label":"Typ média","translatable":false,"required":false,"default":"image","options":[{"value":"image","label":"Fotka (slideshow)"},{"value":"video","label":"Video"}]},{"key":"backgroundImages","type":"image_gallery","label":"Obrázky na pozadí (slideshow)","translatable":false,"required":false,"max":5,"conditional":{"field":"mediaType","value":"image"}},{"key":"videoSource","type":"select","label":"Zdroj videa","translatable":false,"required":false,"default":"external","options":[{"value":"external","label":"External URL (YouTube/Vimeo)"},{"value":"cloudinary","label":"Cloudinary Upload"}],"conditional":{"field":"mediaType","value":"video"}},{"key":"videoUrl","type":"text","label":"URL videa (YouTube/Vimeo embed URL)","translatable":false,"required":false,"placeholder":"https://www.youtube.com/embed/xxxxx","conditional":{"field":"videoSource","value":"external"}},{"key":"cloudinaryVideoId","type":"text","label":"Cloudinary Video ID","translatable":false,"required":false,"placeholder":"sample-video","conditional":{"field":"videoSource","value":"cloudinary"}},{"key":"rotatingText","type":"repeater","label":"Rotující text","translatable":true,"required":false,"min":0,"max":10,"fields":[{"key":"text","type":"text","label":"Text položky","required":true}]},{"key":"ctaButtons","type":"repeater","label":"CTA tlačítka","translatable":true,"required":false,"min":0,"max":3,"fields":[{"key":"text","type":"text","label":"Text tlačítka","required":true},{"key":"url","type":"text","label":"URL odkazu","required":true},{"key":"variant","type":"select","label":"Styl tlačítka","required":true,"options":[{"value":"primary","label":"Primary"},{"value":"secondary","label":"Secondary"},{"value":"outline","label":"Outline"}]}]},{"key":"overlay","type":"checkbox","label":"Tmavý overlay","translatable":false,"required":false,"default":true},{"key":"height","type":"select","label":"Výška sekce","translatable":false,"required":false,"default":"full","options":[{"value":"full","label":"Celá obrazovka"},{"value":"large","label":"Velká"},{"value":"medium","label":"Střední"}]}]}');

-- 2. CTA IMAGE BANNER
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('cta_image_banner', 'CTA Image Banner', 'components/cta-image-banner.php', '📸', 'content', '{"fields":[{"key":"backgroundImage","type":"image","label":"Obrázek na pozadí","translatable":false,"required":true},{"key":"title","type":"text","label":"Nadpis","translatable":true,"required":true},{"key":"subtitle","type":"text","label":"Podnadpis","translatable":true,"required":false},{"key":"buttonText","type":"text","label":"Text tlačítka","translatable":true,"required":true},{"key":"buttonUrl","type":"text","label":"URL odkazu","translatable":false,"required":true},{"key":"buttonVariant","type":"select","label":"Styl tlačítka","translatable":false,"required":false,"default":"primary","options":[{"value":"primary","label":"Primary"},{"value":"secondary","label":"Secondary"},{"value":"outline","label":"Outline"}]},{"key":"overlay","type":"checkbox","label":"Tmavý overlay","translatable":false,"required":false,"default":true}]}');

-- 3. QUOTE (CITACE)
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('quote', 'Citace', 'components/quote-widget.php', '💬', 'content', '{"fields":[{"key":"quoteId","type":"select_dynamic","label":"Citace z databáze","translatable":false,"required":false,"source":"quotes"},{"key":"text","type":"textarea","label":"Vlastní text citace","translatable":true,"required":false},{"key":"author","type":"text","label":"Autor","translatable":true,"required":false},{"key":"role","type":"text","label":"Role autora","translatable":true,"required":false}]}');

-- 4. TEXT BLOCK
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('text_block', 'Textový blok', 'components/text-block.php', '📝', 'content', '{"fields":[{"key":"title","type":"text","label":"Nadpis","translatable":true,"required":false},{"key":"content","type":"wysiwyg","label":"Obsah","translatable":true,"required":true},{"key":"alignment","type":"select","label":"Zarovnání","translatable":false,"required":false,"default":"left","options":[{"value":"left","label":"Vlevo"},{"value":"center","label":"Na střed"},{"value":"right","label":"Vpravo"}]},{"key":"maxWidth","type":"select","label":"Maximální šířka","translatable":false,"required":false,"default":"container","options":[{"value":"container","label":"Container"},{"value":"narrow","label":"Úzké"},{"value":"wide","label":"Široké"},{"value":"full","label":"Celá šířka"}]}]}');

-- 5. VIDEO SECTION
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('video_section', 'Video sekce', 'components/video-section.php', '🎥', 'media', '{"fields":[{"key":"videoId","type":"text","label":"YouTube Video ID","translatable":false,"required":true},{"key":"title","type":"text","label":"Nadpis","translatable":true,"required":false},{"key":"description","type":"textarea","label":"Popis","translatable":true,"required":false},{"key":"aspectRatio","type":"select","label":"Poměr stran","translatable":false,"required":false,"default":"16:9","options":[{"value":"16:9","label":"16:9"},{"value":"4:3","label":"4:3"},{"value":"21:9","label":"21:9"}]},{"key":"autoplay","type":"checkbox","label":"Automatické přehrání","translatable":false,"required":false,"default":false}]}');

-- 6. FEATURE CARDS GRID (2x2)
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('feature_cards_grid', 'Feature Cards Grid (2x2)', 'components/feature-cards-grid.php', '🎴', 'content', '{"fields":[{"key":"sectionTitle","type":"text","label":"Nadpis sekce","translatable":true,"required":false},{"key":"sectionSubtitle","type":"text","label":"Podnadpis sekce","translatable":true,"required":false},{"key":"cards","type":"repeater","label":"Karty","translatable":true,"required":true,"min":2,"max":4,"fields":[{"key":"title","type":"text","label":"Nadpis karty","required":true},{"key":"text","type":"wysiwyg","label":"Text karty","required":true},{"key":"backgroundColor","type":"select","label":"Barva pozadí","required":true,"options":[{"value":"var(--color-brown)","label":"Písková"},{"value":"var(--color-yellow)","label":"Medová"},{"value":"var(--color-blue)","label":"Fjordová"},{"value":"var(--color-red)","label":"Terakota"},{"value":"var(--color-primary)","label":"Zelená"}]}]}]}');

-- 7. FEATURE CARDS WITH IMAGE (1x3)
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('feature_cards_with_image', 'Feature Cards + Obrázky (1x3)', 'components/feature-cards-with-image.php', '🖼️', 'content', '{"fields":[{"key":"sectionTitle","type":"text","label":"Nadpis sekce","translatable":true,"required":false},{"key":"sectionSubtitle","type":"text","label":"Podnadpis sekce","translatable":true,"required":false},{"key":"cards","type":"repeater","label":"Karty","translatable":true,"required":true,"min":1,"max":3,"fields":[{"key":"image","type":"image","label":"Obrázek","required":true},{"key":"title","type":"text","label":"Nadpis","required":true},{"key":"subtitle","type":"text","label":"Podnadpis","required":false},{"key":"text","type":"wysiwyg","label":"Text","required":true},{"key":"backgroundColor","type":"select","label":"Barva pozadí","required":true,"options":[{"value":"var(--color-brown)","label":"Písková"},{"value":"var(--color-yellow)","label":"Medová"},{"value":"var(--color-blue)","label":"Fjordová"},{"value":"var(--color-red)","label":"Terakota"},{"value":"var(--color-primary)","label":"Zelená"}]},{"key":"buttonText","type":"text","label":"Text tlačítka (volitelné)","required":false},{"key":"buttonUrl","type":"text","label":"URL tlačítka (volitelné)","required":false}]}]}');

-- 8. ASYMMETRIC TEXT + VIDEO
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('asymmetric_text_video', 'Asymetrický Text + Video', 'components/asymmetric-text-video.php', '📐', 'layout', '{"fields":[{"key":"text","type":"wysiwyg","label":"Text (barevný blok)","translatable":true,"required":true},{"key":"textBackgroundColor","type":"select","label":"Barva textového bloku","translatable":false,"required":false,"default":"var(--color-primary)","options":[{"value":"var(--color-primary)","label":"Zelená"},{"value":"var(--color-brown)","label":"Písková"},{"value":"var(--color-yellow)","label":"Medová"},{"value":"var(--color-blue)","label":"Fjordová"},{"value":"var(--color-red)","label":"Terakota"}]},{"key":"videoId","type":"text","label":"YouTube Video ID","translatable":false,"required":true},{"key":"aspectRatio","type":"select","label":"Poměr stran videa","translatable":false,"required":false,"default":"16:9","options":[{"value":"16:9","label":"16:9"},{"value":"4:3","label":"4:3"}]}]}');

-- 9. BLOG POSTS GRID
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('blog_posts_grid', 'Blog Posts Grid (3 sloupce)', 'components/blog-posts-grid.php', '📰', 'dynamic', '{"fields":[{"key":"sectionTitle","type":"text","label":"Nadpis sekce","translatable":true,"required":false,"default":"Novinky"},{"key":"limit","type":"number","label":"Počet článků","translatable":false,"required":false,"default":3,"min":1,"max":12},{"key":"showExcerpt","type":"checkbox","label":"Zobrazit perex","translatable":false,"required":false,"default":true},{"key":"showAuthor","type":"checkbox","label":"Zobrazit autora","translatable":false,"required":false,"default":true},{"key":"showDate","type":"checkbox","label":"Zobrazit datum","translatable":false,"required":false,"default":true},{"key":"viewAllButton","type":"checkbox","label":"Tlačítko Všechny články","translatable":false,"required":false,"default":true},{"key":"viewAllButtonText","type":"text","label":"Text tlačítka","translatable":true,"required":false,"default":"Všechny články"}]}');

-- 10. FEATURE CARDS UNIVERSAL (flexibilní)
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('feature_cards_universal', 'Feature Cards (Univerzální)', 'components/feature-cards-universal.php', '🎴', 'content', '{"fields":[{"key":"sectionTitle","type":"text","label":"Nadpis sekce","translatable":true,"required":false},{"key":"sectionSubtitle","type":"text","label":"Podnadpis sekce","translatable":true,"required":false},{"key":"columns","type":"select","label":"Počet sloupců (desktop)","translatable":false,"required":true,"options":[{"value":"1","label":"1 sloupec"},{"value":"2","label":"2 sloupce"},{"value":"3","label":"3 sloupce"},{"value":"4","label":"4 sloupce"}]},{"key":"cards","type":"repeater","label":"Karty","translatable":true,"required":true,"min":1,"fields":[{"key":"image","type":"image","label":"Obrázek (volitelné)","required":false},{"key":"title","type":"text","label":"Nadpis","required":true},{"key":"subtitle","type":"text","label":"Podnadpis (volitelné)","required":false},{"key":"text","type":"wysiwyg","label":"Text","required":true},{"key":"backgroundColor","type":"select","label":"Barva pozadí","required":true,"options":[{"value":"var(--color-brown)","label":"Písková"},{"value":"var(--color-yellow)","label":"Medová"},{"value":"var(--color-blue)","label":"Fjordová"},{"value":"var(--color-red)","label":"Terakota"},{"value":"var(--color-primary)","label":"Zelená"}]},{"key":"buttonText","type":"text","label":"Text tlačítka (volitelné)","required":false},{"key":"buttonUrl","type":"text","label":"URL tlačítka (volitelné)","required":false}]}]}');

-- 11. IMAGE + TEXT (50/50)
INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('image_text', 'Fotka + Text', 'components/image-text.php', '🖼️', 'content', '{"fields":[{"key":"sectionTitle","type":"text","label":"Nadpis sekce (H2)","translatable":true,"required":false},{"key":"sectionSubtitle","type":"text","label":"Podnadpis sekce (H3)","translatable":true,"required":false},{"key":"imagePosition","type":"select","label":"Pozice fotky","translatable":false,"required":false,"default":"left","options":[{"value":"left","label":"Nalevo"},{"value":"right","label":"Napravo"}]},{"key":"image","type":"image","label":"Fotka","translatable":false,"required":true},{"key":"textTitle","type":"text","label":"Nadpis textu (H4)","translatable":true,"required":false},{"key":"textContent","type":"wysiwyg","label":"Text","translatable":true,"required":true},{"key":"backgroundColor","type":"select","label":"Barva pozadí","translatable":false,"required":false,"default":"transparent","options":[{"value":"transparent","label":"Průhledná (výchozí)"},{"value":"var(--color-brown)","label":"Písková"},{"value":"var(--color-yellow)","label":"Medová"},{"value":"var(--color-blue)","label":"Fjordová"},{"value":"var(--color-red)","label":"Terakota"},{"value":"var(--color-primary)","label":"Zelená"}]}]}');

-- =====================================================
-- Seed completed - 11 widget types inserted
-- =====================================================
