-- =====================================================
-- MIGRATION 009: Add Sticky Cards Widget Type
-- =====================================================
-- Widget se sticky kartami, které se na sebe skládají
-- při scrollování. Nadpis je fixní vlevo nebo vpravo.
-- =====================================================

INSERT INTO `widget_types` (`type_key`, `label`, `component_path`, `icon`, `category`, `schema`) VALUES
('sticky_cards', 'Sticky Cards (skládací karty)', 'components/sticky-cards.php', '🃏', 'content', '{"fields":[{"key":"sectionTitle","type":"text","label":"Nadpis sekce","translatable":true,"required":false},{"key":"titlePosition","type":"select","label":"Pozice nadpisu","translatable":false,"required":false,"default":"right","options":[{"value":"left","label":"Vlevo"},{"value":"right","label":"Vpravo"}]},{"key":"sectionBackgroundColor","type":"select","label":"Barva pozadí sekce","translatable":false,"required":false,"default":"var(--color-dark)","options":[{"value":"var(--color-dark)","label":"Tmavá"},{"value":"var(--color-light)","label":"Světlá"},{"value":"var(--color-primary)","label":"Zelená"},{"value":"transparent","label":"Průhledná"}]},{"key":"cards","type":"repeater","label":"Karty","translatable":true,"required":true,"min":2,"max":6,"fields":[{"key":"title","type":"text","label":"Nadpis karty","required":true},{"key":"text","type":"wysiwyg","label":"Text karty","required":true},{"key":"backgroundColor","type":"select","label":"Barva pozadí karty","required":true,"options":[{"value":"var(--color-brown)","label":"Písková"},{"value":"var(--color-yellow)","label":"Medová"},{"value":"var(--color-blue)","label":"Fjordová"},{"value":"var(--color-teal)","label":"Modrozelená"},{"value":"var(--color-red)","label":"Terakota"},{"value":"var(--color-red-alt)","label":"Červená (koralová)"},{"value":"var(--color-primary)","label":"Zelená"},{"value":"var(--color-green)","label":"Zelená (šalvějová)"},{"value":"var(--color-moss)","label":"Zelená (mechová)"},{"value":"var(--color-fjord-dark)","label":"Modrá (fjordová tmavá)"},{"value":"var(--color-raspberry)","label":"Růžová (malinová)"},{"value":"var(--color-sage-dark)","label":"Zelená (šedozelená)"},{"value":"var(--color-lavender)","label":"Levandulová"}]},{"key":"rotation","type":"select","label":"Rotace karty","required":false,"default":"none","options":[{"value":"none","label":"Žádná"},{"value":"slight-left","label":"Mírně vlevo (-3°)"},{"value":"slight-right","label":"Mírně vpravo (3°)"}]},{"key":"buttonText","type":"text","label":"Text tlačítka (volitelné)","required":false},{"key":"buttonUrl","type":"text","label":"URL tlačítka (volitelné)","required":false}]}]}');

-- =====================================================
-- Migration completed - 1 widget type inserted
-- =====================================================
